### ISSUE TITLE
vscoqtop crashes when showing proof state after a tactic

### ISSUE THREAD

**Issue by lukovdm** [coq/vscoq#1035]
I have vscoqtop version 2.2.3 with coq version 8.20.1 installed with the vscoq extension version 2.2.3.
When running in continous mode I can evaluate a proof. However, when I try to step through  a proof with my cursor it vscoqtop crashes with the following error:
```
[top                 , 466313, 1739460348.381356] ==========================================================
[top                 , 466313, 1739460348.381404] Uncaught exception Failure("tag not closed").
[top                 , 466313, 1739460348.381408] ==========================================================
[Error - 16:25:48] Server process exited with code 0.
```
An example short script which causes this for me is:
```coq
Lemma test : False = True -> True.
Proof.
intros H. 
Admitted.
```
Where moving the cursor from before `intros H.` to after it crashes vscoqtop.
Strangely when the lemma is `Lemma test : True -> True.`, this does work.

The same problem also occurs in manual mode when evaluating the intros tactic.

**Comment by gares** [comment]
I think it is fixed in 2.2.4, that is being released now

**Comment by lukovdm** [comment]
I just tested this on 2.2.4, and it still crashes with the same error in the same example.

**Comment by rtetley** [comment]
I will give it a look !

**Comment by lukovdm** [comment]
No, that is the whole file. There are no other files in the vscode project. I have attached the installed packages in opam below. But I don't think I have installed anything weird. Is there a way for me to get more details for you besides that one error?

```
# Packages matching: installed
# Name                # Installed # Synopsis
base                  v0.16.3     Full standard library replacement for OCaml
base-bigarray         base
base-threads          base
base-unix             base
conf-bash             1           Virtual package to install the Bash shell
conf-gmp              4           Virtual package relying on a GMP lib system installation
conf-linux-libc-dev   0           Virtual package relying on the installation of the Linux kernel headers files
conf-pkg-config       4           Check if pkg-config is installed and create an opam switch local pkgconfig folder
coq-core              8.20.1      The Coq Proof Assistant -- Core Binaries and Tools
coq-stdlib            8.20.1      The Coq Proof Assistant -- Standard Library
cppo                  1.8.0       Code preprocessor like cpp for OCaml
csexp                 1.5.2       Parsing and printing of S-expressions in Canonical form
dune                  3.17.2      Fast, portable, and opinionated build system
dune-configurator     3.17.2      Helper library for gathering system configuration
jane-street-headers   v0.16.0     Jane Street C header files
jsonrpc               1.22.0      Jsonrpc protocol implemenation
jst-config            v0.16.0     Compile-time configuration for Jane Street libraries
lsp                   1.22.0      LSP protocol implementation in OCaml
num                   1.5-1       The legacy Num library for arbitrary-precision integer and rational arithmetic
ocaml                 4.14.1      The OCaml compiler (virtual package)
ocaml-base-compiler   4.14.1      Official release 4.14.1
ocaml-compiler-libs   v0.12.4     OCaml compiler libraries repackaged
ocaml-config          2           OCaml Switch Configuration
ocaml-options-vanilla 1           Ensure that OCaml is compiled with no special options enabled
ocamlbuild            0.15.0      OCamlbuild is a build system with builtin rules to easily build most OCaml projects
ocamlfind             1.9.8       A library manager for OCaml
octavius              1.2.2       Ocamldoc comment syntax parser
parsexp               v0.16.0     S-expression parsing library
ppx_assert            v0.16.0     Assert-like extension nodes that raise useful errors on failure
ppx_base              v0.16.0     Base set of ppx rewriters
ppx_cold              v0.16.0     Expands [@cold] into [@inline never][@specialise never][@local never]
ppx_compare           v0.16.0     Generation of comparison functions from types
ppx_derivers          1.2.1       Shared [@@deriving] plugin registry
ppx_deriving          6.0.3       Type-driven code generation for OCaml
ppx_enumerate         v0.16.0     Generate a list containing all values of a finite type
ppx_globalize         v0.16.0     A ppx rewriter that generates functions to copy local values to the global heap
ppx_hash              v0.16.0     A ppx rewriter that generates hash functions from type expressions and definitions
ppx_here              v0.16.0     Expands [%here] into its location
ppx_import            1.11.0      A syntax extension for importing declarations from interface files
ppx_inline_test       v0.16.1     Syntax extension for writing in-line tests in ocaml code
ppx_js_style          v0.16.0     Code style checker for Jane Street Packages
ppx_optcomp           v0.16.0     Optional compilation for OCaml
ppx_sexp_conv         v0.16.0     [@@deriving] plugin to generate S-expression conversion functions
ppx_yojson_conv       v0.16.0     [@@deriving] plugin to generate Yojson conversion functions
ppx_yojson_conv_lib   v0.16.0     Runtime lib for ppx_yojson_conv
ppxlib                0.35.0      Standard infrastructure for ppx rewriters
result                1.5         Compatibility Result module
sel                   0.6.0       Simple Event Library
seq                   base        Compatibility package for OCaml's standard iterator type starting from 4.07.
sexplib               v0.16.0     Library for serializing OCaml values to and from S-expressions
sexplib0              v0.16.0     Library containing the definition of S-expressions and some base converters
stdio                 v0.16.0     Standard IO library for OCaml
stdlib-shims          0.3.0       Backport some of the new stdlib features to older compiler
time_now              v0.16.0     Reports the current time
topkg                 1.0.7       The transitory OCaml software packager
uutf                  1.0.3       Non-blocking streaming Unicode codec for OCaml
vscoq-language-server 2.2.4       VSCoq language server
yojson                2.2.2       Yojson is an optimized parsing and printing library for the JSON format
zarith                1.14        Implements arithmetic and logical operations over arbitrary-precision integers
```

**Comment by thery** [comment]
Can' t reproduce it either. Which version of `code` you are using?

**Comment by thery** [comment]
ok found it. It is when the flag "diff"  is on

**Comment by thery** [comment]
@lukovdm for the moment try to disable the diff mode in the Settings

**Comment by rtetley** [comment]
Okay ! :-) I'll close this as a duplicate of #766 and #866
